language: java
jdk:
  - open: openjdk11

branches:
  only:
    - main
cache:
  directories:
    - '$HOME/Vibecap_Back/.m2/repository'
    - '$HOME/.gradle'

      # script: "./gradlew clean build -x test"
script: "echo $HOME >> hello.txt"

notifications: 
  email: 
    recipients:
      - zammanbo540@naver.com
    on-success: always
    on-failure: always
